services:
  db:
    image: postgres:17
    container_name: image_server_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: images_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: elestio/pgadmin
    container_name: image_server_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db
  app:
    build: .
    container_name: image_server_app
    restart: unless-stopped
    volumes:
      - images:/app/images
      - logs:/app/logs
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
  nginx:
    image: nginx:1.25
    container_name: image_server_nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - images:/images:ro
    ports:
      - "8080:80"
      - "80:80"
    restart: unless-stopped
volumes:
  images:
  logs:
  db_data:
  pgadmin: